version: '3.7'
services:
  tb3-ros:
    container_name: tb3-ros
    image: cosi119/tb3-ros:latest
    ports:
       - '80:6085'
      #- '5900:5900'
       - '6080:6080'
    volumes:
      - type: volume
        source: rospersistent
        target: /my_ros_data
        volume:
          nocopy: false
volumes:
  rospersistent:
    driver_opts:
      type: none
      device: ROSPERSISTENT-PATH
      o: bind
