version: '3.7'
services:
  tb3-ros:
    container_name: tb3-ros
    image: cosi119/tb3-ros:v2.1.0
    ports:
      - '80:80'
      - '2222:2222'
      - '5900:5900'
      - '8080:8080'
    environment:
      PASSWORD: dev@ros
      VNC_PASSWORD: dev@ros
      AUTHKEY: tskey-123abc
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
      - type: volume
        source: rospersistent
        target: /my_ros_data
        volume:
          nocopy: false
volumes:
  rospersistent:
    driver_opts:
      type: none
      device: ROSPERSISTENT-PATH
      o: bind
